#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd "audit/lambda/" || exit

yarn install
yarn lint-staged

cd .. || exit

git diff --cached --name-only | if grep --quiet audit-template.yml
then
  echo "\nRunning Checkov hook...\n"
  checkov -f audit-template.yml --framework cloudformation --quiet --skip-check CKV_AWS_115,CKV_AWS_111,CKV_AWS_116,CKV_AWS_117
fi
