import {
  TEST_AUDIT_BUCKET_NAME,
  TEST_FIREHOSE_DELIVERY_STREAM_NAME,
  TEST_GENERATOR_KEY_ID,
  TEST_PERMANENT_BUCKET_NAME,
  TEST_TEMPORARY_BUCKET_NAME
} from '../testConstants'

process.env.AWS_REGION = 'eu-west-2'
process.env.AUDIT_BUCKET_NAME = TEST_AUDIT_BUCKET_NAME
process.env.AUDIT_PERMANENT_BUCKET_NAME = TEST_PERMANENT_BUCKET_NAME
process.env.AUDIT_TEMPORARY_BUCKET_NAME = TEST_TEMPORARY_BUCKET_NAME
process.env.FIREHOSE_DELIVERY_STREAM_NAME = TEST_FIREHOSE_DELIVERY_STREAM_NAME
process.env.GENERATOR_KEY_ID = TEST_GENERATOR_KEY_ID
