export type EnvironmentVar = {
  name:
    | 'AWS_REGION'
    | 'AUDIT_MESSAGE_DELIMITER_FUNCTION_NAME'
    | 'AUDIT_MESSAGE_DELIVERY_STREAM_LOG_GROUP_NAME'
    | 'FRAUD_HMAC_KEY'
    | 'FRAUD_SPLUNK_DELIVERY_TEST_BUCKET_NAME'
    | 'FRAUD_SPLUNK_TRANSFORMATION_LOG_GROUP_NAME'
    | 'INTEGRATION_TEST_TOPIC_ARN'
    | 'PERFORMANCE_HMAC_KEY'
    | 'PERFORMANCE_SPLUNK_DELIVERY_TEST_BUCKET_NAME'
    | 'PERFORMANCE_SPLUNK_TRANSFORMATION_LOG_GROUP_NAME'
}
