export type EnvironmentVar = {
  name:
    | 'AWS_REGION'
    | 'AUDIT_MESSAGE_DELIMITER_FUNCTION_NAME'
    | 'AUDIT_MESSAGE_DELIMITER_LOGS_NAME'
    | 'S3_COPY_AND_ENCRYPT_FUNCTION_NAME'
    | 'S3_COPY_AND_ENCRYPT_LOGS_NAME'
    | 'FIREHOSE_DELIVERY_STREAM_NAME'
    | 'TEMPORARY_MESSAGE_BATCH_BUCKET_NAME'
    | 'FRAUD_HMAC_KEY'
    | 'AUDIT_BUILD_MESSAGE_BATCH_NAME'
    | 'FIREHOSE_AUDIT_MESSAGE_BATCH_NAME'
}
