export interface EnvironmentVar {
  name:
    | 'AUDIT_BUCKET_NAME'
    | 'AUDIT_PERMANENT_BUCKET_NAME'
    | 'AUDIT_TEMPORARY_BUCKET_NAME'
    | 'AWS_ACCOUNT_ID'
    | 'AWS_REGION'
    | 'FIREHOSE_DELIVERY_STREAM_NAME'
    | 'GENERATOR_KEY_ID'
}
