#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd "event-processing\\lambda\\" || exit

yarn lint-staged

cd .. || exit

git diff --cached --name-only | if grep --quiet template.yaml
then
  echo "\nRunning Checkov hook...\n"
  checkov -f audit-template.yaml --framework cloudformation --quiet
fi

cd .. || exit
cd "audit\\lambda\\" || exit

yarn lint-staged

cd .. || exit

git diff --cached --name-only | if grep --quiet template.yaml
then
  echo "\nRunning Checkov hook...\n"
  checkov -f event-processing-template.yaml --framework cloudformation --quiet
fi

cd .. || exit
cd "analysis\\" || exit

git diff --cached --name-only | if grep --quiet template.yaml
then
  echo "\nRunning Checkov hook...\n"
  checkov -f analysis-template.yaml --framework cloudformation --quiet
fi